### ISSUE TITLE
how to export a backslah?

### ISSUE THREAD

**Issue by fkgruber** [chasberry/orgmode-accessories#38]
Hi
Orgmode replaces \ with \\ when exporting. Do you know any way of preventing this?

The reason I need this is to prevent a double caption issue with quarto:
https://github.com/quarto-dev/quarto-cli/issues/10705

so far I've been having to create a markdown block with the markdown style link

thanks
F

**Comment by chasberry** [comment]
I think you mean that `\` exports as `\\`, right?

You can use an export snippet to force it to export as `\`.

It is a bit confusing (and IMO a defect in the org export conventions) that export snippets do not default to the name of a derived backend. The `md` backend is derived from the `html` backend and does not define its own export-snippet transcoder. So, `@@md: this is markdown@@` is ignored in markdown exports, because the export-snippet transcoder defaults to `html` from the parent backend. And since the `ox-ravel` exports for markdown use the `md` backend as their parent, you should use `html` for ravel markdown export snippets.

So, the idiom you use would be `@@html:\@@`

Alternatively you can use `@@ravel:\@@`, but if you export to another format like `*.Rnw` where the backslash might not be wanted you get it anyway.

**Comment by fkgruber** [comment]
Amazing, thanks.
Did not know about this @@ for inline notation.
